global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8001'] # Simulating EC2 metrics exposure
    # Senior Practice: In a real AWS environment, use 'ec2_sd_configs' to 
    # automatically discover instances based on tags!
